<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.0</TargetFramework>
    <RootNamespace>Tm.Mobile.CoreX</RootNamespace>
    <Authors>Ilia Syrtsov</Authors>
    <Description>Cross-platform Core library</Description>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\Run\Debug</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\Run\Release\</OutputPath>
  </PropertyGroup>

</Project>
